### PR TITLE
Fix for - Internal Server Error When Using Offset >= Total Organizations and Limit = 0 in Organization Discovery GET API 

### PR DESCRIPTION
**Pull request by kumardeepak5**
> **Behavior After Fix:**
> Sample Request: 
```
curl --location 'https://localhost:9443/api/server/v1/organizations/discovery?offset=10&limit=0' \
--header 'Accept: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4='
```
> Sample Response

```
{
    "totalResults": 10,
    "startIndex": 11,
    "count": 0,
    "links": [
        {
            "href": "/api/server/v1/organizations/discovery?offset=10&limit=0",
            "rel": "previous"
        }
    ]
}
```

### CODE REVIEW

**Comment by AnuradhaSK** [comment]
Hi @kumardeepak5 

Thank you for your contribution!

Here, in this case the expected behavior is not to have any previous or next links when the limit = 0. There is no point of giving any previous/next result set accessing URL with offset is 0.

We want to make this API behavior more or less similar to GET `/scim2/Users?startIndex={index}&count={count}` 

Therefore, for this case expected behavior should be:

```
{
    "totalResults": 0,
    "startIndex": 11,
    "count": 0,
    "links": [
     
    ]
}
```

Would you be able to fix in that way?

**Comment by kumardeepak5** [comment]
Hi @AnuradhaSK 
> Therefore, for this case expected behavior should be:
> 
> ```
> {
>     "totalResults": 0,
>     "startIndex": 11,
>     "count": 0,
>     "links": [
>      
>     ]
> }
> ```
> 
> Would you be able to fix in that way?

I have a question about the sample response above: Should the expected value for "totalResults" always be 0 when limit=0, or should it reflect the actual total results? I believe it should reflect the actual total results; could you please confirm?

**Comment by kumardeepak5** [comment]
Hi @AnuradhaSK 
> Therefore, for this case expected behavior should be:
> 
> ```
> {
>     "totalResults": 0,
>     "startIndex": 11,
>     "count": 0,
>     "links": [
>      
>     ]
> }
> ```
> 
> Would you be able to fix in that way?

**The requested changes implemented and below are sample request and response examples after the modifications.**
```
curl --location 'https://localhost:9443/api/server/v1/organizations/discovery?offset=5&limit=0' \
--header 'Authorization: Basic <username:password>'

{
    "totalResults": 5,
    "startIndex": 6,
    "count": 0,
    "links": []
}
```
Please Review.

**Comment by kumardeepak5** [comment]
Hi @AnuradhaSK just a gentle reminder to review the changes.

**Comment by kumardeepak5** [comment]
Related issue is closed.

**Pull request closed without merging**
