### PR TITLE
Remove_validation_for_arbitary_properties

### PR DESCRIPTION
**Pull request by Thumimku**
## Purpose
Resolves https://github.com/wso2/product-is/issues/9965

### CODE REVIEW

**Comment by darshanasbg** [comment]
Why these validations removed?

**Comment by Thumimku** [comment]
> Why these validations removed?

These attributes are arbitrary values, For example POOLING action listener type should have an attribute named **frequency** but WEB_HOOK action listener no need to have. In REST API level, we only create remote fetch configuration object with mandatory fields. For arbitrary params validation must come from back end.

More precisely, 

- Each action listener, config depolyer and repository manager types(Objects) will have their own attributes and their own validation for their fields in backend. 
[https://github.com/wso2-extensions/identity-fetch-remote/blob/master/components/org.wso2.carbon.identity.remotefetch.core/src/main/java/org/wso2/carbon/identity/remotefetch/core/util/RemoteFetchConfigurationValidator.java](https://github.com/wso2-extensions/identity-fetch-remote/blob/master/components/org.wso2.carbon.identity.remotefetch.core/src/main/java/org/wso2/carbon/identity/remotefetch/core/util/RemoteFetchConfigurationValidator.java)

**Comment by darshanasbg** [comment]
Can you point where we do this validation in the backend?

**Comment by Thumimku** [comment]
> Can you point where we do this validation in the backend?

Before Create a new remotefetch configuration we validate their component attributes against their own validation regex.

- Remotefetch Creation service Impl
[https://github.com/wso2-extensions/identity-fetch-remote/blob/master/components/org.wso2.carbon.identity.remotefetch.core/src/main/java/org/wso2/carbon/identity/remotefetch/core/RemoteFetchConfigurationServiceImpl.java#L71](https://github.com/wso2-extensions/identity-fetch-remote/blob/master/components/org.wso2.carbon.identity.remotefetch.core/src/main/java/org/wso2/carbon/identity/remotefetch/core/RemoteFetchConfigurationServiceImpl.java#L71)

- Action Listener Validation check
[https://github.com/wso2-extensions/identity-fetch-remote/blob/master/components/org.wso2.carbon.identity.remotefetch.core/src/main/java/org/wso2/carbon/identity/remotefetch/core/util/RemoteFetchConfigurationValidator.java#L75](https://github.com/wso2-extensions/identity-fetch-remote/blob/master/components/org.wso2.carbon.identity.remotefetch.core/src/main/java/org/wso2/carbon/identity/remotefetch/core/util/RemoteFetchConfigurationValidator.java#L75)

- POOLING action listener component with its own attributes and validation
[https://github.com/wso2-extensions/identity-fetch-remote/blob/master/components/org.wso2.carbon.identity.remotefetch.core/src/main/java/org/wso2/carbon/identity/remotefetch/core/impl/handlers/action/polling/PollingActionListenerComponent.java#L58](https://github.com/wso2-extensions/identity-fetch-remote/blob/master/components/org.wso2.carbon.identity.remotefetch.core/src/main/java/org/wso2/carbon/identity/remotefetch/core/impl/handlers/action/polling/PollingActionListenerComponent.java#L58)

**Review by darshanasbg — APPROVED** [review]

**Pull request merged**
